spring.application.name=dsproject

server.address=0.0.0.0
server.port=8080

#PGPASSWORD=2cPL5r2Xo6q6hI30Xgm8bA4c7YZLjGz6 psql -h dpg-d5bst7er433s7396v4j0-a.frankfurt-postgres.render.com -U dsuser ds_db_name
spring.datasource.url=jdbc:postgresql://dpg-d5bst7er433s7396v4j0-a.frankfurt-postgres.render.com:5432/ds_db_name
spring.datasource.username=dsuser
spring.datasource.password=2cPL5r2Xo6q6hI30Xgm8bA4c7YZLjGz6


# auto generate sql and update db schema at startup
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


#show and format sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#dialect
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

#----------------email---------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=collabworks25@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#-------------------------------------------------
# Session timeout (for development)
server.servlet.session.timeout=30m

# App Properties
app.jwtSecret='ZdHhly8tFaRdsn4pYJSGTSWU678of9GEQhWrTNnzgAXb3vVqdHHUs5QJoWyi87'
app.jwtExpirationMs=86400000