spring.application.name=dsproject

server.address=0.0.0.0
server.port=8080

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# auto generate sql and update db schema at startup
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


#show and format sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#dialect
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

#----------------email---------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#-------------------------------------------------
# Session timeout (for development)
server.servlet.session.timeout=30m

# App Properties
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=86400000